### ISSUE TITLE
Assignment 1 is final and ready for grading!

### ISSUE THREAD

**Issue by melmlr** [SES-5215-F2020/melmiller-quant#1]
I also uploaded the CSV file to Canvas, but you'll see that my Assignment 1 .Rmd, .html, and .csv files are final and ready for grading. I'm excited to continue learning about the dataset and R. Looking forward to hearing your thoughts. 

Thank you! 
Mel

**Comment by melmlr** [comment]
I'm not sure if this has been graded, but I just wanted to direct you to the link: https://ses-5215-f2020.github.io/melmiller-quant/Assignment-1-data-org 

My files are getting a bit overwhelming and I don't believe the final file is totally clear. Thank you!

**Comment by saratepfer** [comment]
Thank you, Mel! Nice job.

**Comments on Code**
Line 13: You shouldn't need to include this line in your markdown file. It can be run in the console.

**Comments on Content**
You are working with a lot of variables! It may be that you narrow down the list as the semester progresses. I agree that your data transformations will depend on what questions you choose to answer/analyses you choose to run. I am looking forward to seeing how your dataset evolves.

**Comment by melmlr** [comment]
Sorry about line 13 @saratepfer! Since I saved over the initial file, that was an addition after submitting the initial assignment. Thank you for this feedback, though. I recognized with Assignment 2 the fact that I'll probably need to remove some variables. Perhaps I'll do so with Assignment 3. Thank you again!
