### ISSUE TITLE
Assignment 5 is ready for grading.

### ISSUE THREAD

**Issue by melmlr** [SES-5215-F2020/melmiller-quant#6]
Hello -- assignment 5 can be viewed [here](https://ses-5215-f2020.github.io/melmiller-quant/Assignment-5_FINAL.html). Thank you!

**Comment by c-voulgaris** [comment]
This looks great. As I think we may have discussed before, 'predicting' age may seem a little odd, so I'll be interested in seeing how you discuss it. One possibility is to think of you model as predicting longevity. For some variables, an association with being older can be understood to be associated with living longer. For instance, that's what you're seeing for the relationship with sex - women live longer than men, so they're older, on average. For others, the causality goes in the reverse direction - having an independent living difficultly doesn't make you live longer, but being older puts you more at risk for developing a disability. You'll need to be thoughtful in how you describe these relationships for the final project.

Is your statement on line 43 a typo? Where are you getting 8%? I see an R-squared value of 0.206, which would mean you're predicting 21% of the variation in age.
